// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcmhaqemtkzjrgxnlgew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbWhhcWVtdGt6anJneG5sZ2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzk3NTMsImV4cCI6MjA2Mjc1NTc1M30.5flJ7zrJtOFnu3MEdhyiEjIJdCzoVJhofrDyppORVYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);